"""added updates

Revision ID: 44097fafd3b7
Revises: 217335cc2f1f
Create Date: 2018-09-10 01:46:45.354772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44097fafd3b7'
down_revision = '217335cc2f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'downvote')
    # ### end Alembic commands ###
